services:
  mssql-b6c:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1434:1433
    volumes:
      - D:/mssql/data:/var/opt/mssql/data
      - D:/mssql/log:/var/opt/mssql/log
      - D:/mssql/secrets:/var/opt/mssql/secrets
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Sa123456