version: "3.3"
services:
  # sql_server:
  #   build: _mssql/
  #   ports:
  #     - 1434:1433
  #   volumes:
  #     - D:/mssql/data:/var/opt/mssql/data
  #     - D:/mssql/log:/var/opt/mssql/log
  #     - D:/mssql/secrets:/var/opt/mssql/secrets
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=Sa123456 # mật khẩu tài khoản sa

  # envoygateway:
  #   # folder chứa file docker
  #   build: _envoy/
  #   ports:
  #     # chỉ định các cổng
  #     - "2900:2900" # cổng gốc
  #     - "3100:3100" # cổng truy cấp http thường và chuyển trang
  #     - "3200:3200" # cổng https
  #   volumes:
  #     - ./_envoy/envoy.yaml:/etc/envoy/envoy.yaml # chuyên gia đọc lệnh
  #     - ./_envoy/https.crt:/etc/ssl/certs/https.crt # chứng chỉ https
  #     - ./_envoy/key.pem:/etc/ssl/certs/key.pem # chứng chỉ https
  #     - D:/envoy/log/envoy:/var/log/envoy #log

  rabbitmq3:
    image: rabbitmq:3.8-management-alpine
    container_name: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER= WT436
      - RABBITMQ_DEFAULT_PASS= WT436
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    volumes:
      - D:/rabbitmq/data/:/var/lib/rabbitmq/
      - D:/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - go_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"


  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    volumes:
      - D:/redis:/var/lib/redis
      - redis_volume_data:/data
      - ./_redis/redis.config:/etc/redis/redis.config
    ports:
      - 6379:6379

  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db
      - D:/redis:/var/lib/redis
volumes:
  redis_volume_data:
  redis_insight_volume_data:
networks:
  go_net:
    driver: bridge
